### ISSUE TITLE
Recipe of glog logging error for SRCREV  

### ISSUE THREAD

**Issue by hutiann** [openembedded/meta-openembedded#160]
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks
WARNING: glog-0.3.5-r0 do_fetch: Failed to fetch URL git://github.com/google/glog.git, attempting MIRRORS if available
ERROR: glog-0.3.5-r0 do_fetch: Fetcher failure: Unable to find revision a6a166db069520dbbd653c97c2e5b12e08a8bb26 in branch master even from upstream
ERROR: glog-0.3.5-r0 do_fetch: Fetcher failure for URL: 'git://github.com/google/glog.git'. Unable to fetch URL from any source.
ERROR: glog-0.3.5-r0 do_fetch: Function failed: base_do_fetch
ERROR: Logfile of failure stored in: /home/user/tda_linux/yocto-build/build/arago-tmp-external-arm-toolchain/work/aarch64-linux/glog/0.3.5-r0/temp/log.do_fetch.91817
ERROR: Task (/home/user/tda_linux/yocto-build/sources/meta-openembedded/meta-oe/recipes-support/glog/glog_0.3.5.bb:do_fetch) failed with exit code '1'

**Comment by kraj** [comment]
its possible that it was intermittent error did you retry again at different time ? otherwise you could also try to change SRC_URI to

`git://github.com/google/glog.git;branch=v035;protocol=https`

thirdly check if you need to bypass proxy
https://wiki.yoctoproject.org/wiki/Working_Behind_a_Network_Proxy
