### ISSUE TITLE
Unable to fetch "tremor" package

### ISSUE THREAD

**Issue by Espiga** [openembedded/meta-openembedded#247]
The following error is happening when fetching the "tremor" package:

```
ERROR: tremor-20180319-r0 do_fetch: Fetcher failure for URL: 'git://gitlab.xiph.org/tremor/tremor.git;protocol=https'. Unable to fetch URL from any source.
```

It seems that Xiph has migrated a few of their repositories to GitLab recently and git.xiph.org seems to have been down for a while.

I am using the branch "zeus" and the related recipe is located inside `meta-multimedia/recipes-multimedia/tremor/`.

**Comment by schnitzeltony** [comment]
There was a patch sent out for zeus - it was not applied. Dis send a ping there

[1] https://lists.openembedded.org/g/openembedded-devel/message/84793

**Comment by kraj** [comment]
@akuster would have to pick it up for Zeus and dunfell

**Comment by akuster** [comment]
the fix is backported to both Dunfell and zeus.

https://git.openembedded.org/meta-openembedded/commit/meta-multimedia/recipes-multimedia/tremor/tremor_20180319.bb?h=dunfell&id=3c79f7f3ec20616f457289978acc777854979b2c

https://git.openembedded.org/meta-openembedded/commit/meta-multimedia/recipes-multimedia/tremor/tremor_20180319.bb?h=zeus&id=2b5dd1eb81cd08bc065bc76125f2856e9383e98b

**Comment by akuster** [comment]
Please update to latest dunfell or zeus
